--[[---------------------------------------------------------------------------
1942 DarkRP - SHOP CATALOGS  (this is the file you edit)

Each catalog is a list of things a dealer can buy. A job uses one with:
    menu = "RP1942_ShopMenu",
    shop = "example",          -- the catalog key below

ITEM FIELDS
    id           unique within the catalog (letters, digits, _)          required
    name         shown in the menu                                        required
    class        weapon or entity class to spawn                          required
    type         "weapon" (spawns as a pickup) or "entity"               required
    price        whole number (the base price)                            required
    ammo         text shown in the Ammo section, e.g. "9x19mm"           optional
    description  text under the name                                      optional
    model        model for the picture (and the weapon pickup);           optional
                 needed for stock HL2 weapons, which have no Lua table
    category     groups items under a heading, in the order written      optional

CATALOG FIELDS
    name         shown under the dealer's name in the menu
    economy      true = prices follow the economy (the German Supplier):
                 cheaper when it's strong, dearer when it's weak. The curve
                 is RP1942.ShopEconomyPricing in sh_shop.lua. Without it,
                 prices are fixed (the Black Market and Cherkesov dealers).

The weapon lists come from the server's weapon sheet. The general "gun
dealer" weapons were split evenly between the Black Market and Cherkesov
dealers (14 each). The ammo line in the menu is read from each weapon.

Only plain data here, no function calls: this file loads before the shop
functions exist (module files load in reverse alphabetical order).

Items whose class doesn't exist yet (placeholders) are safe: the purchase is
refused and no money is taken.
---------------------------------------------------------------------------]]
RP1942 = RP1942 or {}
RP1942.ShopCatalogs = RP1942.ShopCatalogs or {}

RP1942.ShopCatalogs.blackmarket = {
    name = "Black market: fixed prices",
    items = {
        -- Handguns
        { id = "babybrowning", category = "Handguns", class = "mcv_babybrowning", type = "weapon", price = 350,
          name = "Baby Browning",
          description = "A little baby browning handgun, no one takes them serious but with a steady hand and great determination, It just might prove quite deadly." },
        { id = "luger", category = "Handguns", class = "mcv_luger", type = "weapon", price = 800,
          name = "Luger P08",
          description = "A relic of the great war, This german made toggle lock handgun is still quite a coveted and common weapon under the 3rd Reich." },
        { id = "m1911a1", category = "Handguns", class = "mcv_m1911a1", type = "weapon", price = 800,
          name = "M1911A1",
          description = "An american made handgun that is the work horse of the US Army." },
        { id = "c96", category = "Handguns", class = "mcv_c96", type = "weapon", price = 900,
          name = "Mauser C96",
          description = "An relatively old firearm designed before the great war, Still seem to find these from time to time, unique mechanism and loads through the top via stripper clips." },
        { id = "tt33", category = "Handguns", class = "mcv_tt33", type = "weapon", price = 650,
          name = "TT-33",
          description = "A standard issue Soviet hand gun, has moderate fire power but decent rate of fire." },
        { id = "type14", category = "Handguns", class = "mcv_type14", type = "weapon", price = 550,
          name = "Type 14 Nambu",
          description = "Regarded as the Japanese Luger, The Type 14 Nambu is the standard issue handgun of the Japanese Army." },
        { id = "p38", category = "Handguns", class = "mcv_p38", type = "weapon", price = 800,
          name = "Walther P38",
          description = "The Walther P38 is the latest of handguns used by the 3rd reich, prodominately the Wehrmacht." },
        { id = "welrod", category = "Handguns", class = "mcv_welrod", type = "weapon", price = 1500,
          name = "Welrod",
          description = "A British designed bolt action internally suppressed handgun, the weapon is designed for saboteurs and resistance fighters quietly taking out their enemies." },
        -- Revolvers
        { id = "m1917", category = "Revolvers", class = "mcv_m1917", type = "weapon", price = 700,
          name = "M1917",
          description = "An american made service revolver for the US Army." },
        { id = "m1895", category = "Revolvers", class = "mcv_m1895", type = "weapon", price = 550,
          name = "Nagant M1895",
          description = "A Russian Empire revolver originally, many of these would be newly produced Soviet revolvers, Has a 7 round cylinder, How odd." },
        { id = "swm10", category = "Revolvers", class = "mcv_swm10", type = "weapon", price = 650,
          name = "S&W M10",
          description = "An american produced revolver by the Smith and Wesson company, though would be used in limited stockpile for the American Armed forces." },
        -- Submachine guns
        { id = "m45", category = "Submachine guns", class = "mcv_m45", type = "weapon", price = 2200,
          name = "Carl Gustaf M/45",
          description = "An oddly swedish specific submachine gun, not sure how it made it but its cool I guess." },
        { id = "thompson_m1928", category = "Submachine guns", class = "mcv_thompson_m1928", type = "weapon", price = 2800,
          name = "Thompson M1928 'Tommy Gun'",
          description = "The infamous 'Tommy Gun', an american made Submachine gun known to be used by the italian mafia during the 20's in the united states, Now it sees a more noble life supporting the Allied forces." },
        { id = "m3a1", category = "Submachine guns", class = "mcv_m3a1", type = "weapon", price = 1900,
          name = "M3A1 Grease gun",
          description = "The M3A1 Grease gun is a super simple stamped submaching gun made by the General Motors company for the US Army." },
        { id = "m3a1_sog", category = "Submachine guns", class = "mcv_m3a1_sog", type = "weapon", price = 2600,
          name = "Suppressed M3A1 Grease gun",
          description = "A prototype suppressed M3A1 Grease gun, quite popular with resistance and saboteurs." },
        { id = "m50r", category = "Submachine guns", class = "mcv_m50r", type = "weapon", price = 2000,
          name = "M50 Reising",
          description = "A unique american submachine gun with limited use in the US Army, more popular with Marine units in the pacific." },
        { id = "m55r", category = "Submachine guns", class = "mcv_m55r", type = "weapon", price = 2100,
          name = "M55 Reising Para",
          description = "Like the standard M50 Reising, This is a Paratrooper version, with a side folder wire stock making it lighter and more compact." },
        { id = "mas38", category = "Submachine guns", class = "mcv_mas38", type = "weapon", price = 1800,
          name = "MAS-38",
          description = "A french designed submachine gun with particularly terrible sights, but it shoots, so it'll do the job." },
        { id = "mp40", category = "Submachine guns", class = "mcv_mp40", type = "weapon", price = 2400,
          name = "MP-40",
          description = "Incorrectly named as the 'Schmeisser', The MP-40 is the standard issue Submachine gun for the Wehrmacht." },
        { id = "owen", category = "Submachine guns", class = "mcv_owen", type = "weapon", price = 2200,
          name = "Owen Gun",
          description = "A unique top loading submachine gun, is one of the many submachine guns the ANZAC forces use." },
        { id = "pps43", category = "Submachine guns", class = "mcv_pps43", type = "weapon", price = 2100,
          name = "PPS-43",
          description = "A Soviet designed submachine gun, created to replace the more expensive PPSH-41 by being mostly made from stamped parts. It has a significantly lower rate of fire as well in comparison." },
        { id = "ppsh41_drum", category = "Submachine guns", class = "mcv_ppsh41_drum", type = "weapon", price = 2800,
          name = "PPSh-41 Drum",
          description = "The version of the PPSh-41 as the Red Army intended, It includes a 71 round drum magazine." },
        { id = "sten_sog", category = "Submachine guns", class = "mcv_sten_sog", type = "weapon", price = 2300,
          name = "Suppressed Sten MKII",
          description = "A suppressed version of the Sten Mk2, great for infiltration and saboteur missions." },
        -- Shotguns
        { id = "fusil_robust", category = "Shotguns", class = "mcv_fusil_robust", type = "weapon", price = 1100,
          name = "Double Barreled Shotgun",
          description = "A generic brand of double barrel shotgun from who even knows, Great for self defense or demons." },
        { id = "m1897", category = "Shotguns", class = "mcv_m1897", type = "weapon", price = 1600,
          name = "Winchester M1897 'Trench Gun'",
          description = "An American produced shotgun used by the US Army, Also known as the 'Trench Gun', Basically carried the Americans through the great war." },
        { id = "m37", category = "Shotguns", class = "mcv_m37", type = "weapon", price = 1500,
          name = "M37 Ithica",
          description = "A trench gun styled shotgun made by the americans for military use." },
        { id = "fusil_robust_short", category = "Shotguns", class = "mcv_fusil_robust_short", type = "weapon", price = 1000,
          name = "Sawed-Off Double Barrel Shotgun",
          description = "Whats better than two barrels? Two shorter ones, Might not see the benefit of it now, but just think, If you had another one, Maybe you could dual wield them? Hmmm.. Curious.." },
        -- Bolt-action rifles
        { id = "kar98", category = "Bolt-action rifles", class = "mcv_kar98", type = "weapon", price = 1300,
          name = "Karabiner-98K",
          description = "The Standard bolt action rifle of the 3rd Reich." },
        { id = "springfield", category = "Bolt-action rifles", class = "mcv_springfield", type = "weapon", price = 1300,
          name = "Springfield M1903A3",
          description = "The standard issue bolt action rifle of the US Armed Forces." },
        { id = "vz24", category = "Bolt-action rifles", class = "mcv_vz24", type = "weapon", price = 1100,
          name = "Vz. 24",
          description = "Based on the German Gewehr 98 rifles, This Czech bolt action is still quite useful and deadly." },
        -- Battle rifles
        { id = "m1g", category = "Battle rifles", class = "mcv_m1g", type = "weapon", price = 2800,
          name = "M1 Garand",
          description = "Also known as the M1 Rifle, It is the standard battle rifle of the Armed Forces of the United States of America, PING!" },
        -- Sniper rifles
        { id = "kar98_s", category = "Sniper rifles", class = "mcv_kar98_s", type = "weapon", price = 3200,
          name = "Sniper Karabiner-98K",
          description = "A sniper varient of the Kar-98K, great for long distance sniping." },
        { id = "kar98_prewar_s", category = "Sniper rifles", class = "mcv_kar98_prewar_s", type = "weapon", price = 3200,
          name = "Sniper Prewar Karabiner-98K",
          description = "A sniper varient of the Prewar Kar-98K, great for long distance sniping." },
        { id = "m1d", category = "Sniper rifles", class = "mcv_m1d", type = "weapon", price = 3800,
          name = "M1D Garand",
          description = "The sniper version of the M1 Garand rifle, used by the American armed forces." },
        -- Machine guns
        { id = "bren", category = "Machine guns", class = "mcv_bren", type = "weapon", price = 5000,
          name = "Bren",
          description = "An awkward looking light machine gun used by the United Kingdom." },
        { id = "m1918_bar", category = "Machine guns", class = "mcv_m1918_bar", type = "weapon", price = 4800,
          name = "M1918A2 B.A.R. Heavy",
          description = "Much like the standard issue BAR, This version is a heavier version, allowing you to deploy the bipod, but also fit with a higher capacity magazine probably machined somewhere in town." },
        { id = "m1919", category = "Machine guns", class = "mcv_m1919", type = "weapon", price = 6500,
          name = "Browning M1919A6",
          description = "An American belt fed light machinegun, Lots of ammo, not enough germans to kill." },
        { id = "mg43", category = "Machine guns", class = "mcv_mg43", type = "weapon", price = 5800,
          name = "MG-34 Drum",
          description = "Standard issue Machinegun for the 3rd Reich, Uses the smaller Gurttrummel drum magazine." },
        { id = "mg43d", category = "Machine guns", class = "mcv_mg43d", type = "weapon", price = 6400,
          name = "MG-34 w/ Patronentrommel",
          description = "Standard issue Machinegun for the 3rd Reich, Uses a middle ground between the drum and belt, a 75 round Patronentrommel magazine." },
        -- Anti-tank
        { id = "bazooka", category = "Anti-tank", class = "mcv_bazooka", type = "weapon", price = 9000,
          name = "M1A1 Bazooka",
          description = "An american made anti-tank rocket launcher capable of knocking out most medium and heavy german tanks, or just blowing people up." },
        { id = "panzerschreck", category = "Anti-tank", class = "mcv_panzerschreck", type = "weapon", price = 9500,
          name = "Panzerschreck",
          description = "A German designed copy of the M1 Bazooka, The Panzerschreck is a heavier, larger anti-tank rocket launcher. So heavy infact, the previous user removed the protective shield to lighten the load." },
        -- Special
        { id = "crossbow", category = "Special", class = "mcv_crossbow", type = "weapon", price = 700,
          name = "Improvised Crossbow",
          description = "An improvised wooden crossbow, Looks like something from the middle ages." },
        { id = "m9a1", category = "Special", class = "mcv_m9a1", type = "weapon", price = 15000,
          name = "M2 Flamethrower",
          description = "An american made Flamethrower, Great for making kraut barbeques." },
        -- Explosives
        { id = "dynamite", category = "Explosives", class = "mcv_dynamite", type = "weapon", price = 1200,
          name = "Dynamite Bundle",
          description = "A bundle of dynamite with a fuze afixed to it, This can be lit and placed or thrown, Great for ambushes." },
        { id = "m16mine", category = "Explosives", class = "mcv_m16mine", type = "weapon", price = 1500,
          name = "M16 AP Mine",
          description = "An American anti-personnel mine, Its triggered by a tripwire, Great for defending door ways for unsuspecting foes to stumble into." },
        { id = "anm8", category = "Explosives", class = "mcv_anm8", type = "weapon", price = 250,
          name = "AN/M8 Smoke Grenade",
          description = "An American Smoke grenade, great for concealment." },
        { id = "m18", category = "Explosives", class = "mcv_m18", type = "weapon", price = 250,
          name = "M18 Red Smoke Grenade",
          description = "An American Smoke grenade that emits a red colored smoke, used for signaling, but I guess you can use it as concealment, Not sure why you would though." },
        { id = "mk2", category = "Explosives", class = "mcv_mk2", type = "weapon", price = 600,
          name = "Mk2 Frag Grenade",
          description = "An american Fragmentation grenade, Cheap and effective." },
        { id = "mk3a2", category = "Explosives", class = "mcv_mk3a2", type = "weapon", price = 700,
          name = "MK3A2 HE Grenade",
          description = "An American High Explosive grenade, It doesn't produce much shrapnel but it makes up for in explosive power." },
        { id = "molotov", category = "Explosives", class = "mcv_molotov", type = "weapon", price = 400,
          name = "Molotov Cocktail",
          description = "A delightful fiery concoction of alchohol and petrol garnished with a fine strip of cloth to be lit on fire, Instructions as follows: Light cloth on fire, then Throw, Enjoy." },
        { id = "stielhand_smoke", category = "Explosives", class = "mcv_stielhand_smoke", type = "weapon", price = 250,
          name = "Nebelhandgranate",
          description = "A German smoke stick grenade, great for concealment." },
        { id = "css", category = "Explosives", class = "mcv_css", type = "weapon", price = 200,
          name = "RGD-1",
          description = "A Soviet smoke grenade made of cardboard, great for concealment." },
        { id = "stielhand_explosive", category = "Explosives", class = "mcv_stielhand_explosive", type = "weapon", price = 600,
          name = "Stielhandgranate",
          description = "A german fragmentation stick grenade, used by Wehrmacht forces as their primary hand grenade." },
        -- Melee
        { id = "crowbar", category = "Melee", class = "mcv_crowbar", type = "weapon", price = 150,
          name = "Crowbar",
          description = "The Gordon Freeman special." },
        { id = "katana", category = "Melee", class = "mcv_katana", type = "weapon", price = 600,
          name = "Katana",
          description = "A sword that originates from japan, I wonder how it got here?" },
        { id = "m1942_machete", category = "Melee", class = "mcv_m1942_machete", type = "weapon", price = 250,
          name = "M1942 Machete",
          description = "A presumably american machete, useful for cutting down thick brush or pesky germans." },
        { id = "sickle", category = "Melee", class = "mcv_sickle", type = "weapon", price = 150,
          name = "Sickle",
          description = "A long handled sickle used in farming, Now. Where did I put my hammer?" },
        { id = "type30_bayonet", category = "Melee", class = "mcv_type30_bayonet", type = "weapon", price = 200,
          name = "Type 30 Bayonet",
          description = "A japanese bayonet, used for some rifles." },
    },
}

RP1942.ShopCatalogs.cherkesov = {
    name = "Cherkesov's stock: fixed prices",
    items = {
        -- Handguns
        { id = "hipower", category = "Handguns", class = "mcv_hipower", type = "weapon", price = 750,
          name = "Browning Hi-Power",
          description = "A Belgain made, German stolen handgun, surprisingly though, not as High power as the name implies." },
        { id = "mle1935", category = "Handguns", class = "mcv_mle1935", type = "weapon", price = 600,
          name = "MAS-35S",
          description = "A French made pistol, that would see later use by the Germans after France's capitulation." },
        { id = "ruby", category = "Handguns", class = "mcv_ruby", type = "weapon", price = 400,
          name = "Ruby",
          description = "The ruby, which has a longer and very french name, is a small french handgun made during the great war." },
        { id = "type14", category = "Handguns", class = "mcv_type14", type = "weapon", price = 550,
          name = "Type 14 Nambu",
          description = "Regarded as the Japanese Luger, The Type 14 Nambu is the standard issue handgun of the Japanese Army." },
        { id = "ppk", category = "Handguns", class = "mcv_ppk", type = "weapon", price = 1200,
          name = "Suppressed Walther PPK",
          description = "Although typically the Walther PPK would be used by party members of the 3rd reich, This one has been repurposed with a suppressor, Perhaps for spys and saboteurs." },
        -- Revolvers
        { id = "blackhawk", category = "Revolvers", class = "mcv_blackhawk", type = "weapon", price = 900,
          name = "Blackhawk",
          description = "An unsual revolver that resembles something of the old american west, Its got decent firepower, but is single action only, but you can fan it." },
        { id = "lebel", category = "Revolvers", class = "mcv_lebel", type = "weapon", price = 500,
          name = "MAS-M1892",
          description = "A french made service revolver used by the french army before the onset of the great war." },
        { id = "m1895", category = "Revolvers", class = "mcv_m1895", type = "weapon", price = 550,
          name = "Nagant M1895",
          description = "A Russian Empire revolver originally, many of these would be newly produced Soviet revolvers, Has a 7 round cylinder, How odd." },
        -- Submachine guns
        { id = "m45", category = "Submachine guns", class = "mcv_m45", type = "weapon", price = 2200,
          name = "Carl Gustaf M/45",
          description = "An oddly swedish specific submachine gun, not sure how it made it but its cool I guess." },
        { id = "thompson_m1928", category = "Submachine guns", class = "mcv_thompson_m1928", type = "weapon", price = 2800,
          name = "Thompson M1928 'Tommy Gun'",
          description = "The infamous 'Tommy Gun', an american made Submachine gun known to be used by the italian mafia during the 20's in the united states, Now it sees a more noble life supporting the Allied forces." },
        { id = "thompson", category = "Submachine guns", class = "mcv_thompson", type = "weapon", price = 2600,
          name = "M1A1 Thompson",
          description = "The updated, streamlined version of the Thompson submachine gun purpose made for use by the US Army." },
        { id = "thompson_sog", category = "Submachine guns", class = "mcv_thompson_sog", type = "weapon", price = 2500,
          name = "Stockless M1A1 Thompson",
          description = "A stockless version of the M1A1 Thompson sub machinegun." },
        { id = "m3a1", category = "Submachine guns", class = "mcv_m3a1", type = "weapon", price = 1900,
          name = "M3A1 Grease gun",
          description = "The M3A1 Grease gun is a super simple stamped submaching gun made by the General Motors company for the US Army." },
        { id = "owen", category = "Submachine guns", class = "mcv_owen", type = "weapon", price = 2200,
          name = "Owen Gun",
          description = "A unique top loading submachine gun, is one of the many submachine guns the ANZAC forces use." },
        { id = "pps43", category = "Submachine guns", class = "mcv_pps43", type = "weapon", price = 2100,
          name = "PPS-43",
          description = "A Soviet designed submachine gun, created to replace the more expensive PPSH-41 by being mostly made from stamped parts. It has a significantly lower rate of fire as well in comparison." },
        { id = "ppsh41", category = "Submachine guns", class = "mcv_ppsh41", type = "weapon", price = 2400,
          name = "PPSh-41",
          description = "The standard issue soviet Submachine gun, Drum not included.." },
        { id = "ppsh41dd", category = "Submachine guns", class = "mcv_ppsh41dd", type = "weapon", price = 3200,
          name = "PPSh-41 Double Drum",
          description = "A typical model of PPSh-41 but with a large improvised double drum magazine for double the ammo you need to raid any army base." },
        { id = "ppsh41_drum", category = "Submachine guns", class = "mcv_ppsh41_drum", type = "weapon", price = 2800,
          name = "PPSh-41 Drum",
          description = "The version of the PPSh-41 as the Red Army intended, It includes a 71 round drum magazine." },
        { id = "sten", category = "Submachine guns", class = "mcv_sten", type = "weapon", price = 1700,
          name = "Sten MKII",
          description = "The standard issue submachine gun used by British forces, and by extension United Kingdom forces as well." },
        -- Shotguns
        { id = "browning_auto", category = "Shotguns", class = "mcv_browning_auto", type = "weapon", price = 1800,
          name = "Browning Auto 5",
          description = "An american produced semi automatic shotgun." },
        { id = "m1897", category = "Shotguns", class = "mcv_m1897", type = "weapon", price = 1600,
          name = "Winchester M1897 'Trench Gun'",
          description = "An American produced shotgun used by the US Army, Also known as the 'Trench Gun', Basically carried the Americans through the great war." },
        { id = "fusil_robust_short", category = "Shotguns", class = "mcv_fusil_robust_short", type = "weapon", price = 1000,
          name = "Sawed-Off Double Barrel Shotgun",
          description = "Whats better than two barrels? Two shorter ones, Might not see the benefit of it now, but just think, If you had another one, Maybe you could dual wield them? Hmmm.. Curious.." },
        -- Carbines
        { id = "m1_carbine", category = "Carbines", class = "mcv_m1_carbine", type = "weapon", price = 1600,
          name = "M1 Carbine",
          description = "Standard issue carbine of the US Armed Forces." },
        { id = "m1c", category = "Carbines", class = "mcv_m1c", type = "weapon", price = 1700,
          name = "M1A1 Carbine",
          description = "The Paratrooper version of the M1 Carbine rifle, Compact and light." },
        { id = "m1c_sog", category = "Carbines", class = "mcv_m1c_sog", type = "weapon", price = 1600,
          name = "Sawed-off M1A1 Carbine",
          description = "A M1A1 Paratrooper carbine that has been hacked down to be even lighter and compact." },
        { id = "m2c", category = "Carbines", class = "mcv_m2c", type = "weapon", price = 2400,
          name = "M2 Carbine",
          description = "The Full auto version of the M1 Carbine" },
        { id = "m2c_sog", category = "Carbines", class = "mcv_m2c_sog", type = "weapon", price = 2300,
          name = "Sawed-off M2 Carbine",
          description = "A M2 Carbine that has been hacked down to be even lighter and compact." },
        -- Bolt-action rifles
        { id = "kar98_prewar", category = "Bolt-action rifles", class = "mcv_kar98_prewar", type = "weapon", price = 1300,
          name = "Prewar Karabiner-98K",
          description = "A prewar version of the Kar-98K rifle used by the 3rd Reich, Though, if you ask me, Its not any different from the standard issue one." },
        { id = "mas36_cr39", category = "Bolt-action rifles", class = "mcv_mas36_cr39", type = "weapon", price = 1200,
          name = "MAS-36 CR39 Para",
          description = "The MAS-36 CR39 Para, is the paratrooper version of the standard french MAS-36 bolt action rifle." },
        { id = "mas36", category = "Bolt-action rifles", class = "mcv_mas36", type = "weapon", price = 2600,
          name = "MAS-36 w/ Grenade Launcher",
          description = "A standard issue MAS-36 w/ Grenade launcher specific attachments, its able to load and use grenades on the end of the gun." },
        { id = "m38", category = "Bolt-action rifles", class = "mcv_m38", type = "weapon", price = 1100,
          name = "Mosin Nagant M38 Carbine",
          description = "A carbine version of the soviet Mosin Nagant 91/30 Bolt action rifle." },
        { id = "m91", category = "Bolt-action rifles", class = "mcv_m91", type = "weapon", price = 1200,
          name = "Mosin Nagant M91/30",
          description = "The Mosin Nagant M91/30, Known for its 'robust' appearence and terrible ergonomics, yet very powerful." },
        -- Battle rifles
        { id = "avt40", category = "Battle rifles", class = "mcv_avt40", type = "weapon", price = 3000,
          name = "AVT-40",
          description = "A full auto varient of the soviet SVT-40 Battle rifle." },
        { id = "g43", category = "Battle rifles", class = "mcv_g43", type = "weapon", price = 2600,
          name = "Gewehr 43",
          description = "The standard self loading rifle of the 3rd Reich." },
        { id = "m1918", category = "Battle rifles", class = "mcv_m1918", type = "weapon", price = 3800,
          name = "M1918A2 B.A.R.",
          description = "The M1918A2 B.A.R. is a an automatic rifle, intended to support rifle platoons in providing automatic suppressive fire. It features a Fast and Slow fire rate mode for this purpose." },
        { id = "svt40", category = "Battle rifles", class = "mcv_svt40", type = "weapon", price = 2400,
          name = "SVT-40",
          description = "A Standard issue self loading rifle of the Soviet Red Army." },
        -- Assault rifles
        { id = "stg44", category = "Assault rifles", class = "mcv_stg44", type = "weapon", price = 3600,
          name = "StG-44",
          description = "A German automatic rifle with decent firepower and moderate recoil." },
        { id = "stg44_zf41", category = "Assault rifles", class = "mcv_stg44_zf41", type = "weapon", price = 4000,
          name = "StG-44 w/ ZF-41 Scope",
          description = "A German automatic rifle with decent firepower and moderate recoil, with a short range scope for some what longer distance engagements." },
        -- Sniper rifles
        { id = "springfield_s", category = "Sniper rifles", class = "mcv_springfield_s", type = "weapon", price = 3200,
          name = "Springfield M1903A4 Sniper",
          description = "The M1903A4 is an american rifle, purpose built for sniping, supposedly." },
        { id = "m1d", category = "Sniper rifles", class = "mcv_m1d", type = "weapon", price = 3800,
          name = "M1D Garand",
          description = "The sniper version of the M1 Garand rifle, used by the American armed forces." },
        { id = "m38_s", category = "Sniper rifles", class = "mcv_m38_s", type = "weapon", price = 3000,
          name = "Sniper Mosin Nagant M91/30",
          description = "A sniper version of the Mosin Nagant M91/30 rifle." },
        { id = "svt40_s", category = "Sniper rifles", class = "mcv_svt40_s", type = "weapon", price = 3600,
          name = "Sniper SVT-40",
          description = "a sniper version of the SVT-40 battle rifle." },
        -- Machine guns
        { id = "dp28", category = "Machine guns", class = "mcv_dp28", type = "weapon", price = 4800,
          name = "DP-27",
          description = "A Soviet pan magazine feed light machinegun, I refuse to call this thing the DP-28." },
        { id = "fm24", category = "Machine guns", class = "mcv_fm24", type = "weapon", price = 4800,
          name = "FM 24/29",
          description = "A french designed Bren style light machinegun, Quite favorably used by the french army." },
        { id = "m1919", category = "Machine guns", class = "mcv_m1919", type = "weapon", price = 6500,
          name = "Browning M1919A6",
          description = "An American belt fed light machinegun, Lots of ammo, not enough germans to kill." },
        { id = "rp46", category = "Machine guns", class = "mcv_rp46", type = "weapon", price = 6500,
          name = "RP-46",
          description = "A prototype Soviet Light machinegun, Based on the DPM machinegun, it uses a belt fed mechanism to feed ammo into the gun." },
        { id = "rpd", category = "Machine guns", class = "mcv_rpd", type = "weapon", price = 5500,
          name = "RPD",
          description = "A prototype Soviet Light machinegun, A unique machinegun, it uses a drum magazine to feed the ammo into the gun." },
        { id = "rpdb", category = "Machine guns", class = "mcv_rpdb", type = "weapon", price = 6500,
          name = "RPD Belt",
          description = "A prototype Soviet Light machinegun, A unique machinegun, it uses a huge 250 round belt." },
        -- Anti-tank
        { id = "lunge_mine", category = "Anti-tank", class = "mcv_lunge_mine", type = "weapon", price = 3500,
          name = "Lunge Mine",
          description = "An improvised explosive with a preasure plate afixed to a long stick or rod. The user is to run and 'jab' the improvised explosive stick on the target they intend to blow up, Not exactly safe but gets the job done." },
        { id = "ptrd", category = "Anti-tank", class = "mcv_ptrd", type = "weapon", price = 6000,
          name = "PTRD-41",
          description = "A Single shot Soviet Anti-Tank rifle, Chambered in the spicy 14.5mm Caliber, Its capable of penetrating up to an inch or two of wall." },
        { id = "ptrd_sniper", category = "Anti-tank", class = "mcv_ptrd_sniper", type = "weapon", price = 7000,
          name = "Scoped PTRD-41",
          description = "A Single shot Soviet Anti-Tank rifle, Chambered in the spicy 14.5mm Caliber, Its capable of penetrating up to an inch or two of wall and comes with a medium range scope, perfect for sniping through walls or thick glass." },
        -- Special
        { id = "m9a1", category = "Special", class = "mcv_m9a1", type = "weapon", price = 15000,
          name = "M2 Flamethrower",
          description = "An american made Flamethrower, Great for making kraut barbeques." },
        -- Explosives
        { id = "molotov", category = "Explosives", class = "mcv_molotov", type = "weapon", price = 400,
          name = "Molotov Cocktail",
          description = "A delightful fiery concoction of alchohol and petrol garnished with a fine strip of cloth to be lit on fire, Instructions as follows: Light cloth on fire, then Throw, Enjoy." },
        { id = "css", category = "Explosives", class = "mcv_css", type = "weapon", price = 200,
          name = "RGD-1",
          description = "A Soviet smoke grenade made of cardboard, great for concealment." },
        -- Melee
        { id = "m1905_bayonet", category = "Melee", class = "mcv_m1905_bayonet", type = "weapon", price = 200,
          name = "M1905 Bayonet",
          description = "A long bayonet designed for various weapons of the US Army in the mid 1900's." },
        { id = "shovel_ger", category = "Melee", class = "mcv_shovel_ger", type = "weapon", price = 180,
          name = "German Shovel",
          description = "A Standard issue german shovel, great for digging trenches and graves." },
        { id = "wrench", category = "Melee", class = "mcv_wrench", type = "weapon", price = 120,
          name = "Wrench",
          description = "A typical wrench used to tighten nuts or bash them, Up to you I guess." },
    },
}

RP1942.ShopCatalogs.supplier = {
    name = "Reich armoury: prices follow the economy",
    economy = true,
    items = {
        -- Handguns
        { id = "hipower", category = "Handguns", class = "mcv_hipower", type = "weapon", price = 750,
          name = "Browning Hi-Power",
          description = "A Belgain made, German stolen handgun, surprisingly though, not as High power as the name implies." },
        { id = "luger", category = "Handguns", class = "mcv_luger", type = "weapon", price = 800,
          name = "Luger P08",
          description = "A relic of the great war, This german made toggle lock handgun is still quite a coveted and common weapon under the 3rd Reich." },
        { id = "mle1935", category = "Handguns", class = "mcv_mle1935", type = "weapon", price = 600,
          name = "MAS-35S",
          description = "A French made pistol, that would see later use by the Germans after France's capitulation." },
        { id = "c96", category = "Handguns", class = "mcv_c96", type = "weapon", price = 900,
          name = "Mauser C96",
          description = "An relatively old firearm designed before the great war, Still seem to find these from time to time, unique mechanism and loads through the top via stripper clips." },
        { id = "p38", category = "Handguns", class = "mcv_p38", type = "weapon", price = 800,
          name = "Walther P38",
          description = "The Walther P38 is the latest of handguns used by the 3rd reich, prodominately the Wehrmacht." },
        { id = "ppk", category = "Handguns", class = "mcv_ppk", type = "weapon", price = 1200,
          name = "Suppressed Walther PPK",
          description = "Although typically the Walther PPK would be used by party members of the 3rd reich, This one has been repurposed with a suppressor, Perhaps for spys and saboteurs." },
        -- Revolvers
        { id = "lebel", category = "Revolvers", class = "mcv_lebel", type = "weapon", price = 500,
          name = "MAS-M1892",
          description = "A french made service revolver used by the french army before the onset of the great war." },
        -- Submachine guns
        { id = "mp40", category = "Submachine guns", class = "mcv_mp40", type = "weapon", price = 2400,
          name = "MP-40",
          description = "Incorrectly named as the 'Schmeisser', The MP-40 is the standard issue Submachine gun for the Wehrmacht." },
        -- Carbines
        { id = "c96_stock", category = "Carbines", class = "mcv_c96_stock", type = "weapon", price = 2400,
          name = "Mauser M712",
          description = "A Full auto stocked version of the C96 pistol, has a very high rate of fire." },
        -- Bolt-action rifles
        { id = "kar98", category = "Bolt-action rifles", class = "mcv_kar98", type = "weapon", price = 1300,
          name = "Karabiner-98K",
          description = "The Standard bolt action rifle of the 3rd Reich." },
        { id = "kar98_prewar", category = "Bolt-action rifles", class = "mcv_kar98_prewar", type = "weapon", price = 1300,
          name = "Prewar Karabiner-98K",
          description = "A prewar version of the Kar-98K rifle used by the 3rd Reich, Though, if you ask me, Its not any different from the standard issue one." },
        { id = "kar98_zf41", category = "Bolt-action rifles", class = "mcv_kar98_zf41", type = "weapon", price = 1900,
          name = "Kar-98K w/ ZF-41 Scope",
          description = "A Kar-98K with a short ZF-41 scope, A decent choice for short to medium range sniping." },
        { id = "kar98_prewar_zf41", category = "Bolt-action rifles", class = "mcv_kar98_prewar_zf41", type = "weapon", price = 1900,
          name = "Prewar Kar-98K w/ ZF-41 Scope",
          description = "A Prewar Kar-98K with a short ZF-41 scope, A decent choice for short to medium range sniping. Its not that different from the standard." },
        { id = "mas36_cr39", category = "Bolt-action rifles", class = "mcv_mas36_cr39", type = "weapon", price = 1200,
          name = "MAS-36 CR39 Para",
          description = "The MAS-36 CR39 Para, is the paratrooper version of the standard french MAS-36 bolt action rifle." },
        { id = "mas36", category = "Bolt-action rifles", class = "mcv_mas36", type = "weapon", price = 2600,
          name = "MAS-36 w/ Grenade Launcher",
          description = "A standard issue MAS-36 w/ Grenade launcher specific attachments, its able to load and use grenades on the end of the gun." },
        -- Battle rifles
        { id = "g43", category = "Battle rifles", class = "mcv_g43", type = "weapon", price = 2600,
          name = "Gewehr 43",
          description = "The standard self loading rifle of the 3rd Reich." },
        -- Assault rifles
        { id = "stg44", category = "Assault rifles", class = "mcv_stg44", type = "weapon", price = 3600,
          name = "StG-44",
          description = "A German automatic rifle with decent firepower and moderate recoil." },
        { id = "stg44_s", category = "Assault rifles", class = "mcv_stg44_s", type = "weapon", price = 4300,
          name = "StG-44 w/ ZF-4 Scope",
          description = "A German automatic rifle with decent firepower and moderate recoil, with a medium range scope for those longer distance engagements." },
        { id = "stg44_zf41", category = "Assault rifles", class = "mcv_stg44_zf41", type = "weapon", price = 4000,
          name = "StG-44 w/ ZF-41 Scope",
          description = "A German automatic rifle with decent firepower and moderate recoil, with a short range scope for some what longer distance engagements." },
        -- Sniper rifles
        { id = "kar98_s", category = "Sniper rifles", class = "mcv_kar98_s", type = "weapon", price = 3200,
          name = "Sniper Karabiner-98K",
          description = "A sniper varient of the Kar-98K, great for long distance sniping." },
        { id = "kar98_prewar_s", category = "Sniper rifles", class = "mcv_kar98_prewar_s", type = "weapon", price = 3200,
          name = "Sniper Prewar Karabiner-98K",
          description = "A sniper varient of the Prewar Kar-98K, great for long distance sniping." },
        -- Machine guns
        { id = "mg43", category = "Machine guns", class = "mcv_mg43", type = "weapon", price = 5800,
          name = "MG-34 Drum",
          description = "Standard issue Machinegun for the 3rd Reich, Uses the smaller Gurttrummel drum magazine." },
        { id = "mg43b", category = "Machine guns", class = "mcv_mg43b", type = "weapon", price = 7000,
          name = "MG-34 Belt",
          description = "Standard issue Machinegun for the 3rd Reich, Uses a huge 250 round belt." },
        { id = "mg43d", category = "Machine guns", class = "mcv_mg43d", type = "weapon", price = 6400,
          name = "MG-34 w/ Patronentrommel",
          description = "Standard issue Machinegun for the 3rd Reich, Uses a middle ground between the drum and belt, a 75 round Patronentrommel magazine." },
        -- Anti-tank
        { id = "panzerschreck", category = "Anti-tank", class = "mcv_panzerschreck", type = "weapon", price = 9500,
          name = "Panzerschreck",
          description = "A German designed copy of the M1 Bazooka, The Panzerschreck is a heavier, larger anti-tank rocket launcher. So heavy infact, the previous user removed the protective shield to lighten the load." },
        -- Explosives
        { id = "stielhand_smoke", category = "Explosives", class = "mcv_stielhand_smoke", type = "weapon", price = 250,
          name = "Nebelhandgranate",
          description = "A German smoke stick grenade, great for concealment." },
        { id = "stielhand_explosive", category = "Explosives", class = "mcv_stielhand_explosive", type = "weapon", price = 600,
          name = "Stielhandgranate",
          description = "A german fragmentation stick grenade, used by Wehrmacht forces as their primary hand grenade." },
        -- Melee
        { id = "shovel_ger", category = "Melee", class = "mcv_shovel_ger", type = "weapon", price = 180,
          name = "German Shovel",
          description = "A Standard issue german shovel, great for digging trenches and graves." },
    },
}
